### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by HugoPrinsloo** [AfrikaBurn/app_iphone#1]
- [x] Link to the Facebook Page
- [x] Allow the user to open Maps to navigate to the Burn
- [ ] Include cocoapods acknowledgements
- [ ] Link to the official map PDF and handbook

**Comment by HugoPrinsloo** [comment]
### Questions

1. What should be in settings? (Most likely not a audio tour)
2. Are we adding icons? (https://thenounproject.com 👈 is a great place to get amazing icons)

**Comment by danielgalasko** [comment]
Thanks @HugoPrinsloo ! lets get together and discuss this. Will need to source the information etc but so far my thinking is to use iBurn as an example

**Comment by danielgalasko** [comment]
updated @HugoPrinsloo feel free to tackle this :)

**Comment by danielgalasko** [comment]
just published a settings branch

**Comment by danielgalasko** [comment]
feature/settings-page

**Comment by danielgalasko** [comment]
Tackling this one :)
