### ISSUE TITLE
Add a link to listen to Radio Free Tankwa Stream

### ISSUE THREAD

**Issue by DMV-Wayne** [AfrikaBurn/app_iphone#6]
Radio Free Tankwa Rocks

http://www.radiofreetankwa.com/listen.html

**Comment by danielgalasko** [comment]
great idea @DMV-Wayne alas I dont think iOS devices come equipped with an FM/AM receiver 😞

**Comment by DMV-Wayne** [comment]
RFT is a streaming service.

**Comment by Alabandit-AB** [comment]
would need to check if people could link to the local stream in tankwa, and
live stream of site

**Comment by danielgalasko** [comment]
I see, this is a great idea if possible :)

**Comment by DMV-Wayne** [comment]
The streaming is not for at the event.  It is aimed before AB to encourage
people to listen to RFT in their cars before AB.

RFT, needs some exposure.

**Comment by danielgalasko** [comment]
Got it all, looks like there are some links http://www.radiofreetankwa.com/listen.html

Will see what I can do :)

**Comment by DMV-Wayne** [comment]
I recommend to chat to Travis to how he sees it

**Comment by danielgalasko** [comment]
Sure think @DMV-Wayne :)

**Comment by DMV-Wayne** [comment]
Howzit Daniel -

We'd be very happy if RFT could be streamed from phones in vehicles heading
to the event.

I'm copying Patrick and Brian here, as they're our tech-brains trust.





Travis Lyle,

Head of Communications
Skype: hedmekanik1

*Ex Africa semper aliquid novum*

**Comment by danielgalasko** [comment]
Great news @DMV-Wayne I got it working, see attached GIF. Should be in the next update hopefully by end of today

cc @alabandit 

(note, I am doing this in GitHub so I dont have the email thread you do)

![radio-free-tankwa](https://user-images.githubusercontent.com/4479146/38779012-892b27c8-40c2-11e8-8e62-e6a8fe6bd10d.gif)
